# Generated by Django 4.2.5 on 2024-06-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0048_alter_pemusnahanbahanbaku_jumlah'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratjalanpembelian',
            name='NoInvoice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
