# Generated by Django 4.2.5 on 2024-07-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0058_penyesuaian_kodeartikel'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratjalanpenerimaanproduksubkon',
            name='Supplier',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
