# Generated by Django 4.2.5 on 2024-07-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0059_suratjalanpenerimaanproduksubkon_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsuratjalanpengirimanbahanbakusubkon',
            name='KeteranganACC',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
