# Generated by Django 4.2.5 on 2024-07-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0060_detailsuratjalanpengirimanbahanbakusubkon_keteranganacc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailsuratjalanpengirimanbahanbakusubkon',
            name='KeteranganACC',
        ),
        migrations.AddField(
            model_name='detailsuratjalanpenerimaanproduksubkon',
            name='KeteranganACC',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
