# Generated by Django 4.2.5 on 2024-07-07 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0061_remove_detailsuratjalanpengirimanbahanbakusubkon_keteranganacc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailsuratjalanpenerimaanproduksubkon',
            old_name='IDDetailSJPengirimanSubkon',
            new_name='IDDetailSJPenerimaanSubkon',
        ),
    ]
